import { BurnRequest, AuditLog, Farm, Patrol, Front, UserProfile } from './types';

// ============================================================================
// CATÁLOGO OFICIAL DE FRENTES - INGENIO LA UNIÓN
// ============================================================================
export const INITIAL_FRONTS: Front[] = [
  {
    id: 'fr-15',
    name: 'Frente 15',
    code: 'FR-15',
    harvest_type: 'Mecanizada',
    supervisor_turno_a: 'Christian Josue Perez Car',
    supervisor_turno_b: 'Oscar Geovany Villalobos Ixcal',
    active: true,
  },
  {
    id: 'fr-16',
    name: 'Frente 16',
    code: 'FR-16',
    harvest_type: 'Mecanizada',
    supervisor_turno_a: 'Moises Elizardo Argueta',
    supervisor_turno_b: 'Marvin Castillo',
    active: true,
  },
  {
    id: 'fr-17',
    name: 'Frente 17',
    code: 'FR-17',
    harvest_type: 'Manual',
    supervisor_turno_a: 'Angel Leonardo Ortega',
    supervisor_turno_b: 'Elio Omar Noguera',
    active: true,
  },
  {
    id: 'fr-19',
    name: 'Frente 19',
    code: 'FR-19',
    harvest_type: 'Manual',
    supervisor_turno_a: 'Leidy Johana Nij Velasquez',
    supervisor_turno_b: 'Marlon Jehu Colorado',
    active: true,
  },
  {
    id: 'fr-23',
    name: 'Frente 23',
    code: 'FR-23',
    harvest_type: 'Mixta',
    supervisor_turno_a: 'Wendy Fabiola Aguirre',
    supervisor_turno_b: 'Rosa Lopez',
    active: true,
  },
  {
    id: 'fr-25',
    name: 'Frente 25',
    code: 'FR-25',
    harvest_type: 'Mecanizada',
    supervisor_turno_a: 'Oslin Corina Mazariegos',
    supervisor_turno_b: 'Milton Pineda Ovalle',
    active: true,
  },
];

// ============================================================================
// FINCAS DEL INGENIO LA UNIÓN
// ============================================================================
export const INITIAL_FARMS: Farm[] = [
  { id: 'f-1', name: 'Finca Las Palmas', code: 'LP-01', zone: 'Zona Sur - Costa', active: true },
  { id: 'f-2', name: 'Finca El Trapiche', code: 'ET-02', zone: 'Zona Sur - Costa', active: true },
  { id: 'f-3', name: 'Finca San Jerónimo', code: 'SJ-03', zone: 'Zona Central', active: true },
  { id: 'f-4', name: 'Finca La Esperanza', code: 'LE-04', zone: 'Zona Central', active: true },
  { id: 'f-5', name: 'Finca Santa Rosa', code: 'SR-05', zone: 'Zona Norte', active: true },
  { id: 'f-6', name: 'Finca Los Almendros', code: 'LA-06', zone: 'Zona Norte', active: true },
  { id: 'f-7', name: 'Finca San Francisco', code: 'SF-07', zone: 'Zona Oriente', active: true },
  { id: 'f-8', name: 'Finca Miramar', code: 'MM-08', zone: 'Zona Costa', active: true },
];

// ============================================================================
// PATRULLAS / CLAVES DE QUEMA - INGENIO LA UNIÓN (OFICIAL ZAFRA 56)
// ============================================================================
export const INITIAL_PATROLS: Patrol[] = [
  {
    id: 'pat-ruben',
    name: 'Clave RUBEN',
    leader_name: 'Erlin Oswaldo Cruz (Supervisor)',
    shift_info: 'Turno de Día',
    crew_members: ['Axel Jesús Arévalo Jacobo', 'Jefri Antonio Arévalo Jacobo', 'Kleiver David Rodas Rivera'],
    phone: '+502 5555-0100',
    vehicle_code: 'RUBEN-01',
    status: 'DISPONIBLE',
    active: true,
  },
  {
    id: 'pat-c1',
    name: 'Clave C-1',
    leader_name: 'Eder Santos / Carlos Orellana / Lester Yucuteco / Edy Arévalo',
    shift_info: 'Turno de 8 Horas',
    crew_members: [
      'Edy David García Galindo',
      'María Angélica Ortiz Catalán',
      'Brener Alexander Sosof Cruz',
      'Sergio Geovany González',
      'Jeremías de Jesús González',
      'Milvia Paola Morales Ramos',
      'Fredy Fernando Rivera',
      'Edwin Ottoniel Méndez',
      'Sherlyn Milene Rodríguez',
      'Ingrid Marielos Del Cid',
      'Edgar Daniel Sifontes',
      'Gerardo Roberto Telón',
    ],
    phone: '+502 5555-0101',
    vehicle_code: 'C1-401',
    status: 'DISPONIBLE',
    active: true,
  },
  {
    id: 'pat-c2',
    name: 'Clave C-2',
    leader_name: 'Orlando Manfredo Calderón / José Emanuel Colindres',
    shift_info: 'Doble Turno 12 Horas',
    crew_members: [
      'Edwin Joel Orellana García',
      'Alexandra Yesenia Gálvez del Cid',
      'Melvin Fernando Lara Ortiz',
      'Gelber Vidail Bautista Ramírez',
      'Emerson Daniel García Rodríguez',
      'Roxana Maribel Barillas Cruz',
    ],
    phone: '+502 5555-0102',
    vehicle_code: 'C2-402',
    status: 'DISPONIBLE',
    active: true,
  },
  {
    id: 'pat-c3',
    name: 'Clave C-3',
    leader_name: 'Cristian Manaury Salazar / Gustavo Adolfo Del Cid',
    shift_info: 'Doble Turno 12 Horas',
    crew_members: [
      'Silvia Patricia Larios Tomás',
      'Alfonso Gámez Elvira',
      'Henrry Jeovani Calderón',
      'Lesvin Eduardo Cedillos Hernández',
      'Jorge Antonio Gutiérrez Silva',
      'Jerson Abimael Surec Pedroza',
    ],
    phone: '+502 5555-0103',
    vehicle_code: 'C3-403',
    status: 'DISPONIBLE',
    active: true,
  },
  {
    id: 'pat-c4',
    name: 'Clave C-4',
    leader_name: 'Katerin Julissa García / David Dubón Arenas',
    shift_info: 'Doble Turno 12 Horas',
    crew_members: [
      'Joel Marcedonio Surec Castellanos',
      'Jerson Abimael Surec Pedroza',
      'Bladimir Espinoza Gámez',
      'Augusto Daniel Santos López',
      'Jacquelin Roxana Estrada Martínez',
      'Eliezer Baudilio Sáenz Pichola',
    ],
    phone: '+502 5555-0104',
    vehicle_code: 'C4-404',
    status: 'DISPONIBLE',
    active: true,
  },
  {
    id: 'pat-c5',
    name: 'Clave C-5',
    leader_name: 'César Agusto Larios',
    shift_info: '12 Horas Turno de Día',
    crew_members: [
      'Alix Morales y Morales',
      'Alexander Morales Juracán',
      'Alexander Antonio Chan Xitumul',
    ],
    phone: '+502 5555-0105',
    vehicle_code: 'C5-405',
    status: 'DISPONIBLE',
    active: true,
  },
  {
    id: 'pat-c6',
    name: 'Clave C-6',
    leader_name: 'Bryan Antonio Alvarenga Lima',
    shift_info: 'Turno de Día',
    crew_members: [
      'Gerver Rolando Rivera',
      'Heilyn Aylin García Guzmán',
      'Edgar Baldemar Say',
    ],
    phone: '+502 5555-0106',
    vehicle_code: 'C6-406',
    status: 'DISPONIBLE',
    active: true,
  },
  {
    id: 'pat-c7',
    name: 'Clave C-7',
    leader_name: 'Junior Oswaldo Mendoza / Edvin Waldemar Guarán',
    shift_info: 'Turno de Día',
    crew_members: [
      'Allas Iván Valdez',
      'Evelyn Cecilia Florián Chocoy',
      'Harrison Leonardo del Cid Morales',
      'Wilfred Joel Bautista Ramírez',
      'Bonifacio Corado Cayax',
    ],
    phone: '+502 5555-0107',
    vehicle_code: 'C7-407',
    status: 'DISPONIBLE',
    active: true,
  },
];

// ============================================================================
// USUARIOS OFICIALES DE INGENIO LA UNIÓN (FRENTES, DESCANSOS, QUEMAS, DIGITADOR, JEFATURA)
// ============================================================================
export const INITIAL_USERS: UserProfile[] = [
  // FRENTE 15
  {
    id: 'usr-frente-15a',
    username: 'christian.perez',
    password: 'frente123',
    pin: '1501',
    full_name: 'Christian Josue Perez Car',
    email: 'christian.perez@launion.com',
    role: 'supervisor_frente',
    phone: '+502 5555-1501',
    assigned_front: 'Frente 15',
    current_shift: 'Turno Día (06:00 - 18:00)',
    active: true,
  },
  {
    id: 'usr-frente-15b',
    username: 'oscar.villalobos',
    password: 'frente123',
    pin: '1502',
    full_name: 'Oscar Geovany Villalobos Ixcal',
    email: 'oscar.villalobos@launion.com',
    role: 'supervisor_frente',
    phone: '+502 5555-1502',
    assigned_front: 'Frente 15',
    current_shift: 'Turno Noche (18:00 - 06:00)',
    active: true,
  },

  // FRENTE 16
  {
    id: 'usr-frente-16a',
    username: 'moises.argueta',
    password: 'frente123',
    pin: '1601',
    full_name: 'Moises Elizardo Argueta',
    email: 'moises.argueta@launion.com',
    role: 'supervisor_frente',
    phone: '+502 5555-1601',
    assigned_front: 'Frente 16',
    current_shift: 'Turno Día (06:00 - 18:00)',
    active: true,
  },
  {
    id: 'usr-frente-16b',
    username: 'marvin.castillo',
    password: 'frente123',
    pin: '1602',
    full_name: 'Marvin Castillo',
    email: 'marvin.castillo@launion.com',
    role: 'supervisor_frente',
    phone: '+502 5555-1602',
    assigned_front: 'Frente 16',
    current_shift: 'Turno Noche (18:00 - 06:00)',
    active: true,
  },

  // FRENTE 17
  {
    id: 'usr-frente-17a',
    username: 'angel.ortega',
    password: 'frente123',
    pin: '1701',
    full_name: 'Angel Leonardo Ortega',
    email: 'angel.ortega@launion.com',
    role: 'supervisor_frente',
    phone: '+502 5555-1701',
    assigned_front: 'Frente 17',
    current_shift: 'Turno Día (06:00 - 18:00)',
    active: true,
  },
  {
    id: 'usr-frente-17b',
    username: 'elio.noguera',
    password: 'frente123',
    pin: '1702',
    full_name: 'Elio Omar Noguera',
    email: 'elio.noguera@launion.com',
    role: 'supervisor_frente',
    phone: '+502 5555-1702',
    assigned_front: 'Frente 17',
    current_shift: 'Turno Noche (18:00 - 06:00)',
    active: true,
  },

  // FRENTE 19
  {
    id: 'usr-frente-19a',
    username: 'leidy.nij',
    password: 'frente123',
    pin: '1901',
    full_name: 'Leidy Johana Nij Velasquez',
    email: 'leidy.nij@launion.com',
    role: 'supervisor_frente',
    phone: '+502 5555-1901',
    assigned_front: 'Frente 19',
    current_shift: 'Turno Día (06:00 - 18:00)',
    active: true,
  },
  {
    id: 'usr-frente-19b',
    username: 'marlon.colorado',
    password: 'frente123',
    pin: '1902',
    full_name: 'Marlon Jehu Colorado',
    email: 'marlon.colorado@launion.com',
    role: 'supervisor_frente',
    phone: '+502 5555-1902',
    assigned_front: 'Frente 19',
    current_shift: 'Turno Noche (18:00 - 06:00)',
    active: true,
  },

  // FRENTE 23
  {
    id: 'usr-frente-23a',
    username: 'wendy.aguirre',
    password: 'frente123',
    pin: '2301',
    full_name: 'Wendy Fabiola Aguirre',
    email: 'wendy.aguirre@launion.com',
    role: 'supervisor_frente',
    phone: '+502 5555-2301',
    assigned_front: 'Frente 23',
    current_shift: 'Turno Día (06:00 - 18:00)',
    active: true,
  },
  {
    id: 'usr-frente-23b',
    username: 'rosa.lopez',
    password: 'frente123',
    pin: '2302',
    full_name: 'Rosa Lopez',
    email: 'rosa.lopez@launion.com',
    role: 'supervisor_frente',
    phone: '+502 5555-2302',
    assigned_front: 'Frente 23',
    current_shift: 'Turno Noche (18:00 - 06:00)',
    active: true,
  },

  // FRENTE 25
  {
    id: 'usr-frente-25a',
    username: 'oslin.mazariegos',
    password: 'frente123',
    pin: '2501',
    full_name: 'Oslin Corina Mazariegos',
    email: 'oslin.mazariegos@launion.com',
    role: 'supervisor_frente',
    phone: '+502 5555-2501',
    assigned_front: 'Frente 25',
    current_shift: 'Turno Día (06:00 - 18:00)',
    active: true,
  },
  {
    id: 'usr-frente-25b',
    username: 'milton.pineda',
    password: 'frente123',
    pin: '2502',
    full_name: 'Milton Pineda Ovalle',
    email: 'milton.pineda@launion.com',
    role: 'supervisor_frente',
    phone: '+502 5555-2502',
    assigned_front: 'Frente 25',
    current_shift: 'Turno Noche (18:00 - 06:00)',
    active: true,
  },

  // SUPERVISORES DE RELEVO / COBERTURA DE DESCANSOS (Desc1 & Desc2)
  {
    id: 'usr-frente-desc1',
    username: 'rodolfo.samayoa',
    password: 'frente123',
    pin: '9001',
    full_name: 'Rodolfo Elvira Samayoa (Descanso 1 / Relevo)',
    email: 'rodolfo.samayoa@launion.com',
    role: 'supervisor_frente',
    phone: '+502 5555-9001',
    assigned_front: 'Frente 15',
    current_shift: 'Relevo / Cobertura de Descanso',
    is_relief_supervisor: true,
    active: true,
  },
  {
    id: 'usr-frente-desc2',
    username: 'jaqueline.muxin',
    password: 'frente123',
    pin: '9002',
    full_name: 'Jaqueline Viviana Muxin (Descanso 2 / Relevo)',
    email: 'jaqueline.muxin@launion.com',
    role: 'supervisor_frente',
    phone: '+502 5555-9002',
    assigned_front: 'Frente 16',
    current_shift: 'Relevo / Cobertura de Descanso',
    is_relief_supervisor: true,
    active: true,
  },

  // ==========================================================================
  // SUPERVISOR GENERAL DE QUEMAS
  // ==========================================================================
  {
    id: 'usr-quemas-erlin',
    username: 'erlin.cruz',
    password: 'quemas123',
    pin: '1001',
    full_name: 'Erlin Oswaldo Cruz',
    email: 'erlin.cruz@launion.com',
    role: 'supervisor_quemas',
    phone: '+502 5555-0201',
    assigned_patrol_name: 'Clave RUBEN',
    active: true,
  },

  // ==========================================================================
  // PATRULLAS / ENCARGADOS DE QUEMAS (CLAVES C-1 A C-7)
  // ==========================================================================
  // CLAVE C-1 (Turno de 8 Horas)
  {
    id: 'usr-pat-c1-1',
    username: 'eder.santos',
    password: 'patrulla123',
    pin: '101',
    full_name: 'Eder Adelso Santos López',
    email: 'eder.santos@launion.com',
    role: 'patrulla',
    phone: '+502 5555-0101',
    assigned_patrol_id: 'pat-c1',
    assigned_patrol_name: 'Clave C-1',
    active: true,
  },
  {
    id: 'usr-pat-c1-2',
    username: 'carlos.orellana',
    password: 'patrulla123',
    pin: '102',
    full_name: 'Carlos Denilson Orellana Pérez',
    email: 'carlos.orellana@launion.com',
    role: 'patrulla',
    phone: '+502 5555-0102',
    assigned_patrol_id: 'pat-c1',
    assigned_patrol_name: 'Clave C-1',
    active: true,
  },
  {
    id: 'usr-pat-c1-3',
    username: 'lester.yucuteco',
    password: 'patrulla123',
    pin: '103',
    full_name: 'Lester Danilo Yucuteco Carballos',
    email: 'lester.yucuteco@launion.com',
    role: 'patrulla',
    phone: '+502 5555-0103',
    assigned_patrol_id: 'pat-c1',
    assigned_patrol_name: 'Clave C-1',
    active: true,
  },
  {
    id: 'usr-pat-c1-4',
    username: 'edy.arevalo',
    password: 'patrulla123',
    pin: '104',
    full_name: 'Edy Fernando Arévalo Figueroa',
    email: 'edy.arevalo@launion.com',
    role: 'patrulla',
    phone: '+502 5555-0104',
    assigned_patrol_id: 'pat-c1',
    assigned_patrol_name: 'Clave C-1',
    active: true,
  },

  // CLAVE C-2 (Doble Turno 12 Horas)
  {
    id: 'usr-pat-c2-1',
    username: 'orlando.calderon',
    password: 'patrulla123',
    pin: '201',
    full_name: 'Orlando Manfredo Calderón López',
    email: 'orlando.calderon@launion.com',
    role: 'patrulla',
    phone: '+502 5555-0201',
    assigned_patrol_id: 'pat-c2',
    assigned_patrol_name: 'Clave C-2',
    active: true,
  },
  {
    id: 'usr-pat-c2-2',
    username: 'jose.colindres',
    password: 'patrulla123',
    pin: '202',
    full_name: 'José Emanuel Colindres',
    email: 'jose.colindres@launion.com',
    role: 'patrulla',
    phone: '+502 5555-0202',
    assigned_patrol_id: 'pat-c2',
    assigned_patrol_name: 'Clave C-2',
    active: true,
  },

  // CLAVE C-3 (Doble Turno 12 Horas)
  {
    id: 'usr-pat-c3-1',
    username: 'cristian.salazar',
    password: 'patrulla123',
    pin: '301',
    full_name: 'Cristian Manaury Salazar Cobar',
    email: 'cristian.salazar@launion.com',
    role: 'patrulla',
    phone: '+502 5555-0301',
    assigned_patrol_id: 'pat-c3',
    assigned_patrol_name: 'Clave C-3',
    active: true,
  },
  {
    id: 'usr-pat-c3-2',
    username: 'gustavo.delcid',
    password: 'patrulla123',
    pin: '302',
    full_name: 'Gustavo Adolfo Del Cid Monzón',
    email: 'gustavo.delcid@launion.com',
    role: 'patrulla',
    phone: '+502 5555-0302',
    assigned_patrol_id: 'pat-c3',
    assigned_patrol_name: 'Clave C-3',
    active: true,
  },

  // CLAVE C-4 (Doble Turno 12 Horas)
  {
    id: 'usr-pat-c4-1',
    username: 'katerin.garcia',
    password: 'patrulla123',
    pin: '401',
    full_name: 'Katerin Julissa García González',
    email: 'katerin.garcia@launion.com',
    role: 'patrulla',
    phone: '+502 5555-0401',
    assigned_patrol_id: 'pat-c4',
    assigned_patrol_name: 'Clave C-4',
    active: true,
  },
  {
    id: 'usr-pat-c4-2',
    username: 'david.dubon',
    password: 'patrulla123',
    pin: '402',
    full_name: 'David Dubón Arenas',
    email: 'david.dubon@launion.com',
    role: 'patrulla',
    phone: '+502 5555-0402',
    assigned_patrol_id: 'pat-c4',
    assigned_patrol_name: 'Clave C-4',
    active: true,
  },

  // CLAVE C-5 (12 Horas Turno de Día)
  {
    id: 'usr-pat-c5-1',
    username: 'cesar.larios',
    password: 'patrulla123',
    pin: '501',
    full_name: 'César Agusto Larios',
    email: 'cesar.larios@launion.com',
    role: 'patrulla',
    phone: '+502 5555-0501',
    assigned_patrol_id: 'pat-c5',
    assigned_patrol_name: 'Clave C-5',
    active: true,
  },

  // CLAVE C-6 (Turno de Día)
  {
    id: 'usr-pat-c6-1',
    username: 'bryan.alvarenga',
    password: 'patrulla123',
    pin: '601',
    full_name: 'Bryan Antonio Alvarenga Lima',
    email: 'bryan.alvarenga@launion.com',
    role: 'patrulla',
    phone: '+502 5555-0601',
    assigned_patrol_id: 'pat-c6',
    assigned_patrol_name: 'Clave C-6',
    active: true,
  },

  // CLAVE C-7 (Turno de Día)
  {
    id: 'usr-pat-c7-1',
    username: 'junior.mendoza',
    password: 'patrulla123',
    pin: '701',
    full_name: 'Junior Oswaldo Mendoza Cruz',
    email: 'junior.mendoza@launion.com',
    role: 'patrulla',
    phone: '+502 5555-0701',
    assigned_patrol_id: 'pat-c7',
    assigned_patrol_name: 'Clave C-7',
    active: true,
  },
  {
    id: 'usr-pat-c7-2',
    username: 'edvin.guaran',
    password: 'patrulla123',
    pin: '702',
    full_name: 'Edvin Waldemar Guarán Estrada',
    email: 'edvin.guaran@launion.com',
    role: 'patrulla',
    phone: '+502 5555-0702',
    assigned_patrol_id: 'pat-c7',
    assigned_patrol_name: 'Clave C-7',
    active: true,
  },

  // DIGITADOR
  {
    id: 'usr-digitador-1',
    username: 'oscar.morales',
    password: 'Launion123',
    pin: '7645',
    full_name: 'Oscar Josue Morales Herrera',
    email: 'oscar.morales@launion.com',
    role: 'digitador',
    phone: '+502 5555-0401',
    active: true,
  },

  // JEFATURA
  {
    id: 'usr-jefatura-1',
    username: 'fernando.alvarado',
    password: 'jefatura123',
    pin: '5001',
    full_name: 'Lic. Fernando Alvarado',
    email: 'fernando.alvarado@launion.com',
    role: 'jefatura',
    phone: '+502 5555-0501',
    active: true,
  },
];

const now = new Date();
const todayStr = (hours: number, minutes: number) => {
  const d = new Date(now);
  d.setHours(hours, minutes, 0, 0);
  return d.toISOString();
};

// ============================================================================
// SOLICITUDES DE QUEMA INICIALES (VACÍO PARA PRUEBAS REALES)
// ============================================================================
export const INITIAL_BURNS: BurnRequest[] = [];

// ============================================================================
// BITÁCORA DE AUDITORÍA INICIAL (VACÍO PARA PRUEBAS REALES)
// ============================================================================
export const INITIAL_AUDIT_LOGS: AuditLog[] = [];
